### PR TITLE
Introduced bootstrap CSS overrides and updated readme.md

### PR DESCRIPTION
**Pull request by baherramzy**
Big no-no here in that my API key is pushed. Tried excluding via .gitignore but that hasn't had an effect apparently. Unsure about the file mode changes either. Help appreciated!

### CODE REVIEW

**Comment by iBotPeaches** [comment]
So ignoring all the changes that were accidental and not supposed to be here, I see the main change is
- adding instructions to README
- adding css override for alert class (is this to center alert messages?)

The mode changes might be caused by your editor, operating system or something. You should leverage `git`s ability to only stage files you change. IE `git checkout -b updating_readme` & `git add README.me`, `git commit` (write the commit message, use `:wq` to leave it) then `git push origin updating_readme`

**Comment by baherramzy** [comment]
Yes, the overrides file is to accommodate any bootstrap style overrides we might wish to have in the future. Bootstraps alert class is `text-align: left;` by default so I elected to center it. 

Any thoughts on how to exclude the API credentials?

**Comment by bladefist** [comment]
@baherramzy From this commit or future? I could delete the PR and have you redo it.  You should git ignore the file that has the api key in it.  I use sourcetree for git which makes this all very easy.

**Comment by baherramzy** [comment]
@bladefist That's what I tried [here](https://github.com/baherramzy/DestinyStatus/blob/46784023295c84aad0223d54c64fdf94582d85d1/.gitignore) on line 8, but for some reason it didn't take effect.

**Comment by sgtfrankieboy** [comment]
If you can rebase your commits so it doesn't contain the changes to `destiny.php` and all the `.gitignore` files we can pull the changes.

The `destiny.php` file isn't in the .gitignore file because it contains important code for the setup of the project.

**Comment by baherramzy** [comment]
Thanks everyone, PR updated to have only the necessary changes.

**Pull request merged**
