### PR TITLE
Adds checklist for Nightfall and Daily PVE

### LINKED ISSUE #3: Nightfall does not show up in character checklist
Another breaking api change.

### PR DESCRIPTION
**Pull request by iBotPeaches**
- removes arena/raids calls (6) in favor of 3 pve calls (net -3 calls)
- manually checks advisor hash of daily instead of ActivityType
- comments out old calls vs removing
- adds nightfall/daily to weekly tab
- fixes #3 

Hold off on merging this yet. I need to check 3 things
 1) ~~~That `PoE` games show up in `AllPvE`. I haven't done a `PoE` in ages, so need to do one.~~~
 2) ~~~Lemme see if the daily works tomorrow after reset to ensure my code for getting daily is right~~~

test2

### CODE REVIEW

**Comment by frodeknutsen** [comment]
This is so sweet. The tab should perhaps be renamed to "Checklist" or something similar though since it now includes a daily activity.

**Comment by iBotPeaches** [comment]
test

This is good now. Arenas correctly trigger, raids trigger & daily and nightfall.

**Comment by Mulchman** [comment]
Might as well as daily/weekly/Nightfall PvP if you're going to go this
route, a la www.destinychecklist.net

**Comment by Mulchman** [comment]
Might as well *add (sorry, replying via phone).

**Comment by iBotPeaches** [comment]
A whole different beast to include PvP daily/weekly. It would be an additional 3 requests. Trying to cut down on those, but still keep the site fast and feature packed.

**Pull request merged**
